/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utfpr.edu.br.view.telas.login;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author Bernardo
 */
public class LoginViewImpl extends javax.swing.JFrame implements LoginView{

    /**
     * Creates new form LoginView
     */
    ActionListener butaoListener;
    public LoginViewImpl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelJogar = new javax.swing.JPanel();
        btJogar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        jtfJogar1 = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelJogar.setOpaque(false);

        btJogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTAO_NORMAL.png")));
         btJogar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTAO_ON_FOCUS.png")));// NOI18N

        lbNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LabelNome.png"))); // NOI18N
        lbNome.setName("lbName"); // NOI18N

        jtfJogar1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jtfJogar1.setName("jtfNome"); // NOI18N

        lbSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label_Senha.png"))); // NOI18N
        lbSenha.setName("lbSenha");


        jPasswordField1.setPreferredSize(new java.awt.Dimension(6, 50));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout panelJogarLayout = new javax.swing.GroupLayout(panelJogar);
        panelJogar.setLayout(panelJogarLayout);
        panelJogarLayout.setHorizontalGroup(
            panelJogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJogarLayout.createSequentialGroup()
                .addGroup(panelJogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelJogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelJogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelJogarLayout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(jtfJogar1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelJogarLayout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addComponent(btJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelJogarLayout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(lbNome))))
                        .addGroup(panelJogarLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        panelJogarLayout.setVerticalGroup(
            panelJogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJogarLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfJogar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panelJogar, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forca.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginViewImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginViewImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginViewImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginViewImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginViewImpl().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jtfJogar1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPanel panelJogar;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getBotaoLogin() {
        return btJogar;
    }

    @Override
    public String getSenha() {
        return jPasswordField1.getText();
    }
    @Override
    public String getNome() {
        System.out.println(jtfJogar1.getText());
        return jtfJogar1.getText();
    }
    @Override
    public void addAutenticarListener(ActionListener listener) {
       btJogar.addActionListener(listener);
    }

    @Override
    public Component getJFrame() {
        return this;
    }

    @Override
    public void packAndShow() {
        this.pack();
        this.setVisible(true);
    }

    @Override
    public void clearFields() {
        Component[] componentes = this.getContentPane().getComponents();

        for (int i = 0; i < componentes.length; i++) {
            if (componentes[i] instanceof JTextField) {
                JTextField field = (JTextField)componentes[i];
                field.setText("");
            }
        }
    }
}
